### ISSUE TITLE
add table of contents plugin to markdown-it 

### ISSUE THREAD

**Issue by AlahmadiQ8** [reptar/reptar#54]
the only one i found that appears to be maintained is [this one](https://github.com/Oktavilla/markdown-it-table-of-contents)

it would used by adding [[toc]] anywhere in the markdown file like this: 

``` markdown

# Heading 1 

[[toc]]

...
....
...
```

Here is [an example](https://github.com/AlahmadiQ8/reptar/commit/fe7ce992e287c7c6bd1bb167f1d843e0310cd90f) of how i did it on my fork. I'd need to add options in the _config.yaml for the [plugin options](https://github.com/AlahmadiQ8/reptar/commit/fe7ce992e287c7c6bd1bb167f1d843e0310cd90f). Right now they're hard coded. 
- How would you go about this? 
- Another option is to write my own toc generator and make it aa reptar plugin instead. I'd do it similarly to [reptar-excerp](https://github.com/reptar/reptar-excerpt). Then, on the file frontmatter, you can add an option `toc: true`. 

what do you think ?

**Comment by hswolff** [comment]
Oh this is a great idea!

I do agree that allowing this to be added via a plugin makes the most sense as then anyone can easily extend their installation and include any plugins that they want.

I'm trying to think of the proper API for this.

Right now my current thought is to have an `Plugin.event.reptar.afterUpdate()` function that will get run at the [end of the `update()` command](http://github.com/reptar/reptar/blob/d7e63502592f04481320a08c25e4b90ad5ab4447/lib/index.js#L169).

My main question now is what should be given to the plugin event that allows for customization. I'm half tempted to give the `reptar` instance, however that still won't give you access to the markdown instance. So that's the last piece of the puzzle to figure out.

**Comment by AlahmadiQ8** [comment]
Thank you. I will try to think about it as well in the meantime.

**Comment by hswolff** [comment]
Got a flexible solution pushed out in version 2.3.0 https://github.com/reptar/reptar/blob/master/CHANGELOG.md#230-2016-11-06
